kind: ConfigMap
apiVersion: v1
metadata:
  name: nginxelasticsearch
data:
  elasticsearch.conf: |
    location /_plugin/ {
      proxy_pass http://elasticsearch.{STACKNAME}.us-east-1.phoenix.mobileiron.com/_plugin/;
      proxy_pass_request_headers off;
      proxy_set_header HOST $host;
      proxy_set_header Referer $http_referer;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
