apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-deployment
  namespace: monitoring
  labels:
     app: alertmanager
spec:
   replicas: 1
   selector:
     matchLabels:
       app: alertmanager
   template:
      metadata:
         labels:
           app: alertmanager
      spec:
        containers:
         - name: alertmanager
           image: prom/alertmanager
           volumeMounts:
              - name: alertmanager-config
                mountPath: /etc/alertmanager/alertmanager.yml
                subPath: alertmanager.yml
              - name: alertmanager-storage-volume
                mountPath: /alertmanager/
           ports:
           - containerPort: 9093
        volumes:
        - name: alertmanager-config
          configMap:
            name: alertmanager-config

        - name: alertmanager-storage-volume
          persistentVolumeClaim:
            claimName: hackathon-epam
