apiVersion: v1
kind: PersistentVolume
metadata:
  name: hackathon-epam
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: ""
    path: "/nfshackathon"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hackathon-epam
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi