apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |-
    instance_name = grafana
    [log]
    mode = console
    [server]
    root_url = http://grafana-service.monitoring.svc.cluster.local:3000/grafana
    [auth.anonymous]
    # enable anonymous access
    enabled = true
    # specify role for unauthenticated users
    org_role = Admin
  datasource.yaml: |-
    apiVersion: 1
    deleteDatasources:
      - name: Graphite
        orgId: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.monitoring.svc.cluster.local:8080/
        editable: true
  dashboards.yaml: |-
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      updateIntervalSeconds: 10
      options:
        path: /usr/share/grafana/public/dashboards/
